org: daisuke1tanabe
app: serverless-express
service: serverless-express
frameworkVersion: '3'

package:
  individually: true

custom:
  # https://github.com/floydspace/serverless-esbuild?tab=readme-ov-file#options
  esbuild:
    bundle: true
    minify: false
    concurrency: 8
    zipConcurrency: 8
    target: "node20"
    # https://github.com/floydspace/serverless-esbuild?tab=readme-ov-file#serverless-offline
    watch:
      pattern: ['src/**/*.ts']

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-northeast-1
  profile: daisuke-admin

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-better-credentials
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-esbuild
